export const MONITOR_DELAY = 60000;
export const MONITOR_DELAY_ON_PAUSE = 120000;

export const STATUS_PRIORITY = [
  'QUEUED', 'READY_TO_DELIVERY', 'IN_ORDER', 'COLLECTED', 'READY_TO_STORAGE', 
  'TO_STORAGE', 'RETURNED', 'VISIT_DONE', 'TO_NEXT_VISIT', 'VISIT_SUSPENDED',
  'VISIT_CANCELED', 'CREATED', 'STORAGED', 'DELIVERED', 'LOST'];

export const SERVICE_TYPE_PRIORITY = ['ON_DEMAND', 'SAME_DAY', 'NEXT_DAY'];

export const EVIDENCE_FILE_BASE_PATH = 'Resources\\Images\\';

export const HOME_PAGE_PATH = 'home';

export const LOGIN_PAGE_PATH = 'login';

export const STATUS_ICONS = {
  CREATED: 'ellipse',
  QUEUED: 'help-circle',
  IN_ORDER: 'navigate',
  COLLECTED: 'navigate',
  READY_TO_STORAGE: 'archive',
  READY_TO_DELIVERY: 'navigate',
  DELIVERED: 'checkmark-done-circle',
  TO_STORAGE: 'archive',
  TO_NEXT_VISIT: 'help-circle',
  VISIT_DONE: 'alert-circle',
  STORAGED: 'archive',
  VISIT_CANCELED: 'warning',
  DELETED: 'close-circle',
  VISIT_SUSPENDED: 'warning',
  RETURNED: 'warning',
  LOST: 'warning'
};

export const STATUS = {
  CREATED: 'CREATED',
  QUEUED: 'QUEUED',
  IN_ORDER: 'IN_ORDER',
  DELIVERED: 'DELIVERED',
  COLLECTED: 'COLLECTED',
  READY_TO_STORAGE: 'READY_TO_STORAGE',
  READY_TO_DELIVERY: 'READY_TO_DELIVERY',
  TO_STORAGE: 'TO_STORAGE',
  VISIT_DONE: 'VISIT_DONE',
  VISIT_CANCELED: 'VISIT_CANCELED',
  VISIT_SUSPENDED: 'VISIT_SUSPENDED',
  RETURNED: 'RETURNED',
  TO_NEXT_VISIT: 'TO_NEXT_VISIT',
  STORAGED: 'STORAGED'
};

export const SERVICE = {
  ON_DEMAND: 'ON_DEMAND',
  SAME_DAY: 'SAME_DAY',
  NEXT_DAY: 'NEXT_DAY'
};

export const STATUS_ICON_COLOR = {
  'ON_DEMAND': {
    CREATED: 'danger',
    QUEUED: 'danger',
    IN_ORDER: 'danger',
    COLLECTED: '',
    READY_TO_STORAGE: 'tertiary',
    READY_TO_DELIVERY: 'success',
    DELIVERED: 'success',
    TO_STORAGE: 'tertiary',
    TO_NEXT_VISIT: '',
    VISIT_DONE: 'danger',
    STORAGED: 'success',
    VISIT_CANCELED: 'danger',
    DELETED: '',
    VISIT_SUSPENDED: 'warning',
    RETURNED: 'danger',
    LOST: ''
  },
  'SAME_DAY': {
    CREATED: 'warning',
    QUEUED: 'danger',
    IN_ORDER: 'warning',
    COLLECTED: '',
    READY_TO_STORAGE: 'tertiary',
    READY_TO_DELIVERY: 'success',
    DELIVERED: 'success',
    TO_STORAGE: 'tertiary',
    TO_NEXT_VISIT: '',
    VISIT_DONE: 'danger',
    STORAGED: 'success',
    VISIT_CANCELED: 'danger',
    DELETED: '',
    VISIT_SUSPENDED: 'warning',
    RETURNED: 'danger',
    LOST: ''
  },
  'NEXT_DAY': {
    CREATED: 'secondary',
    QUEUED: 'warning',
    IN_ORDER: 'tertiary',
    COLLECTED: 'tertiary',
    READY_TO_STORAGE: 'tertiary',
    READY_TO_DELIVERY: 'success',
    DELIVERED: 'success',
    TO_STORAGE: 'tertiary',
    TO_NEXT_VISIT: '',
    VISIT_DONE: 'danger',
    STORAGED: 'success',
    VISIT_CANCELED: 'danger',
    DELETED: '',
    VISIT_SUSPENDED: 'warning',
    RETURNED: 'danger',
    LOST: ''
  }
}

export const ORDER_PROGRESS = {
  CREATED: 0.1,
  QUEUED: 0.1,
  IN_ORDER: 0.25,
  COLLECTED: 0.5,
  RETURNED: 0.5,
  READY_TO_DELIVERY: 0.75,
  READY_TO_STORAGE: 0.75,
  TO_STORAGE: 0.75,
  DELIVERED: 1,
  STORAGED: 1,
  LOST: 1,
  VISIT_DONE: 0.5,
  TO_NEXT_VISIT: 0.2,
  VISIT_CANCELED: 0.5,
  VISIT_SUSPENDED: 0.5
};

export const ORDER_PROGRESS_COLOR = {
  CREATED: 'secondary',
  QUEUED: 'secondary',
  IN_ORDER: 'primary',
  COLLECTED: 'primary',
  RETURNED: 'warning',
  READY_TO_DELIVERY: 'primary',
  READY_TO_STORAGE: 'primary',
  TO_STORAGE: 'primary',
  DELIVERED: 'success',
  STORAGED: 'success',
  LOST: 'danger',
  VISIT_DONE: 'warning',
  TO_NEXT_VISIT: 'tertiary',
  VISIT_CANCELED: 'warning',
  VISIT_SUSPENDED: 'warning'
};

export const KEYS = {
  APP: {
    NAME: 'APP.NAME',
    WAITING_NEW_ORDERS: 'APP.WAITING_NEW_ORDERS',
    NEW_ORDER_MESSAGE: 'APP.NEW_ORDER_MESSAGE',
    NEW_ORDERS_MESSAGE: 'APP.NEW_ORDERS_MESSAGE',
    NEW_ORDER_TITLE: 'APP.NEW_ORDER_TITLE',
    CHANGES_TO_STATUS: 'APP.CHANGES_TO_STATUS',
    ORDER_UPDATED_TITLE: 'APP.ORDER_UPDATED_TITLE'
  },
  LOADING: 'LOADING',
  ORDERS: 'ORDERS',
  ORDER: 'ORDER',
  CLOSE: 'CLOSE',
  YES: 'YES',
  NO: 'NO',
  SEARCH: 'SEARCH',
  ACTIONS: 'ACTIONS',
  DIRECTIONS: 'DIRECTIONS',
  MINUTES: 'MINUTES',
  REJECT: 'REJECT',
  TAKE: 'TAKE',
  SUSPEND: 'SUSPEND',
  COLLECT: 'COLLECT',
  TO_STORAGE: 'To TO_STORAGE',
  DELIVERY: 'DELIVERY',
  STORE: 'STORE',
  FAIL: 'FAIL',
  DONE: 'DONE',
  REJECTED: 'REJECTED',
  TAKED: 'TAKED',
  SUSPENDED: 'SUSPENDED',
  COLLECTED: 'COLLECTED',
  DELIVERED: 'DELIVERED',
  STORED: 'STORED',
  IN_DELIVERY: 'IN_DELIVERY',
  IN_WAREHOUSE: 'IN_WAREHOUSE',

  LOGIN_PAGE: {
    SIGN_IN: 'LOGIN_PAGE.SIGN_IN',
    USERNAME: 'LOGIN_PAGE.USERNAME',
    PASSWORD: 'LOGIN_PAGE.PASSWORD',
    AUTHENTICATING: 'LOGIN_PAGE.AUTHENTICATING',
    AUTH_FAILED: 'LOGIN_PAGE.AUTH_FAILED'
  },

  HOME_PAGE: {
    TITLE: 'HOME_PAGE.TITLE',
    NO_ORDERS: 'HOME_PAGE.NO_ORDERS',
    MODE_ONLINE: 'HOME_PAGE.MODE_ONLINE',
    AUTOTAKE: 'HOME_PAGE.AUTOTAKE'
  },
  
  ORDER_PAGE: {
    CONFIRM_REJECT: 'ORDER_PAGE.CONFIRM_REJECT',
    CONFIRM_SUSPEND: 'ORDER_PAGE.CONFIRM_SUSPEND',
    ORDER_ASSIGNED: 'ORDER_ASSIGNED',
    REJECTED_MESSAGE: 'ORDER_PAGE.REJECTED_MESSAGE',
    SUSPENDED_MESSAGE: 'ORDER_PAGE.SUSPENDED_MESSAGE',
    COLLECTED_MESSAGE: 'ORDER_PAGE.COLLECTED_MESSAGE',
    ON_WAY_TO_WAREHOUSE: 'ORDER_PAGE.ON_WAY_TO_WAREHOUSE',
    IN_DELIVERY: 'ORDER_PAGE.IN_DELIVERY',
    IN_THE_WAREHOUSE: 'ORDER_PAGE.IN_THE_WAREHOUSE',
    COULD_NOT_BE_DELIVERED: 'ORDER_PAGE.COULD_NOT_BE_DELIVERED',
    WAS_DELIVERED: 'ORDER_PAGE.WAS_DELIVERED'
  },
  VIEW_ORDER_PAGE: {
    IS_LOST: 'VIEW_ORDER_PAGE.IS_LOST',
    REPORT_AS_LOST: 'VIEW_ORDER_PAGE.REPORT_AS_LOST',
    GO_TO_STORAGE: 'VIEW_ORDER_PAGE.GO_TO_STORAGE',
    GO_TO_DELIVERY: 'VIEW_ORDER_PAGE.GO_TO_DELIVERY',
    RETURNED_BY_RECIPIENT: 'VIEW_ORDER_PAGE.RETURNED_BY_RECIPIENT',
    DELIVERY_FAILED: 'VIEW_ORDER_PAGE.DELIVERY_FAILED',
    SUCCESSFULLY_DELIVERED: 'VIEW_ORDER_PAGE.SUCCESSFULLY_DELIVERED',
    GENERAL: 'VIEW_ORDER_PAGE.GENERAL',
    DIRECTIONS: 'VIEW_ORDER_PAGE.DIRECTIONS',
    PACKAGES: 'VIEW_ORDER_PAGE.PACKAGES',
    LOG: 'VIEW_ORDER_PAGE.LOG'
  },
  DIRECTIONS_COMPONENT: {
    PICKUP: 'DIRECTIONS_COMPONENT.PICKUP',
    DROPOFF: 'DIRECTIONS_COMPONENT.DROPOFF',
    SELECT_DELIVERED_EVIDENCE_FILE: 'DIRECTIONS_COMPONENT.SELECT_DELIVERED_EVIDENCE_FILE',
    SELECT_COLLECTED_EVIDENCE_FILE: 'DIRECTIONS_COMPONENT.SELECT_COLLECTED_EVIDENCE_FILE',
    ERROR_UPLOADING_EVIDENCE_FILE: 'DIRECTIONS_COMPONENT.ERROR_UPLOADING_EVIDENCE_FILE'
  },
  GENERAL_COMPONENT: {
    INFORMATION: 'GENERAL_COMPONENT.INFORMATION',
    CUSTOMER: 'GENERAL_COMPONENT.CUSTOMER',
    TIME: 'GENERAL_COMPONENT.TIME',
    DISTANCE: 'GENERAL_COMPONENT.DISTANCE',
    SERVICE: 'GENERAL_COMPONENT.SERVICE',
    DATE: 'GENERAL_COMPONENT.DATE',
    STATUS: 'GENERAL_COMPONENT.STATUS'
  },
  LOG_COMPONENT: {
    DATE: 'LOG_COMPONENT.DATE',
    NOTES: 'LOG_COMPONENT.NOTES',
    PREVIOUS: 'LOG_COMPONENT.PREVIOUS',
    STATUS: 'LOG_COMPONENT.STATUS',
    EVIDENCE: 'LOG_COMPONENT.EVIDENCE'
  },
  PACKAGE_COMPONENT: {
    PACKAGE: 'PACKAGE_COMPONENT.PACKAGE'
  },
  EVIDENCE_PREVIEW_COMPONENT: {
    EVIDENCE_OF: 'EVIDENCE_PREVIEW_COMPONENT.EVIDENCE_OF',
    REMOVE_EVIDENCE: 'EVIDENCE_PREVIEW_COMPONENT.REMOVE_EVIDENCE',
    REMOVE_EVIDENCE_QUESTION: 'EVIDENCE_PREVIEW_COMPONENT.REMOVE_EVIDENCE_QUESTION',
    CANCEL: 'EVIDENCE_PREVIEW_COMPONENT.CANCEL',
    REMOVE: 'EVIDENCE_PREVIEW_COMPONENT.REMOVE'
  },
  SERVICE_TYPE: {
    UNKNOW: 'SERVICE_TYPE.UNKNOW',
    SHORT: {
      ON_DEMAND: 'SERVICE_TYPE.SHORT.ON_DEMAND',
      SAME_DAY: 'SERVICE_TYPE.SHORT.SAME_DAY',
      NEXT_DAY: 'SERVICE_TYPE.SHORT.NEXT_DAY'
    },
    LONG: {
      ON_DEMAND: 'SERVICE_TYPE.LONG.ON_DEMAND',
      SAME_DAY: 'SERVICE_TYPE.LONG.SAME_DAY',
      NEXT_DAY: 'SERVICE_TYPE.LONG.NEXT_DAY'
    }
  },
  STATUS: {
    UNKNOW: 'STATUS.UNKNOW',
    CREATED: {
      SHORT: 'STATUS.CREATED.SHORT',
      ACTION: 'STATUS.CREATED.ACTION',
      LONG: 'STATUS.CREATED.LONG'
    },
    QUEUED: {
      SHORT: 'STATUS.QUEUED.SHORT',
      ACTION: 'STATUS.QUEUED.ACTION',
      LONG: 'STATUS.QUEUED.LONG'
    },
    IN_ORDER: {
      SHORT: 'STATUS.IN_ORDER.SHORT',
      ACTION: 'STATUS.IN_ORDER.ACTION',
      LONG: 'STATUS.IN_ORDER.LONG'
    },
    COLLECTED: {
      SHORT: 'STATUS.COLLECTED.SHORT',
      ACTION: 'STATUS.COLLECTED.ACTION',
      LONG: 'STATUS.COLLECTED.LONG'
    },
    READY_TO_STORAGE: {
      SHORT: 'STATUS.READY_TO_STORAGE.SHORT',
      ACTION: 'STATUS.READY_TO_STORAGE.ACTION',
      LONG: 'STATUS.READY_TO_STORAGE.LONG'
    },
    READY_TO_DELIVERY: {
      SHORT: 'STATUS.READY_TO_DELIVERY.SHORT',
      ACTION: 'STATUS.READY_TO_DELIVERY.ACTION',
      LONG: 'STATUS.READY_TO_DELIVERY.LONG'
    },
    DELIVERED: {
      SHORT: 'STATUS.DELIVERED.SHORT',
      ACTION: 'STATUS.DELIVERED.ACTION',
      LONG: 'STATUS.DELIVERED.LONG'
    },
    TO_STORAGE: {
      SHORT: 'STATUS.TO_STORAGE.SHORT',
      ACTION: 'STATUS.TO_STORAGE.ACTION',
      LONG: 'STATUS.TO_STORAGE.LONG'
    },
    TO_NEXT_VISIT: {
      SHORT: 'STATUS.TO_NEXT_VISIT.SHORT',
      ACTION: 'STATUS.TO_NEXT_VISIT.ACTION',
      LONG: 'STATUS.TO_NEXT_VISIT.LONG'
    },
    VISIT_DONE: {
      SHORT: 'STATUS.VISIT_DONE.SHORT',
      ACTION: 'STATUS.VISIT_DONE.ACTION',
      LONG: 'STATUS.VISIT_DONE.LONG'
    },
    STORAGED: {
      SHORT: 'STATUS.STORAGED.SHORT',
      ACTION: 'STATUS.STORAGED.ACTION',
      LONG: 'STATUS.STORAGED.LONG'
    },
    VISIT_CANCELED: {
      SHORT: 'STATUS.VISIT_CANCELED.SHORT',
      ACTION: 'STATUS.VISIT_CANCELED.ACTION',
      LONG: 'STATUS.VISIT_CANCELED.LONG'
    },
    DELETED: {
      SHORT: 'STATUS.DELETED.SHORT',
      ACTION: 'STATUS.DELETED.ACTION',
      LONG: 'STATUS.DELETED.LONG'
    },
    VISIT_SUSPENDED: {
      SHORT: 'STATUS.VISIT_SUSPENDED.SHORT',
      ACTION: 'STATUS.VISIT_SUSPENDED.ACTION',
      LONG: 'STATUS.VISIT_SUSPENDED.LONG'
    },
    RETURNED: {
      SHORT: 'STATUS.RETURNED.SHORT',
      ACTION: 'STATUS.RETURNED.ACTION',
      LONG: 'STATUS.RETURNED.LONG'
    },
    LOST: {
      SHORT: 'STATUS.LOST.SHORT',
      ACTION: 'STATUS.LOST.ACTION',
      LONG: 'STATUS.LOST.LONG'
    }
  },
  PACKAGE_SIZE: {
    ENVELOP: 'PACKAGE_SIZE.ENVELOP',
    SMALL: 'PACKAGE_SIZE.SMALL',
    MEDIUM: 'PACKAGE_SIZE.MEDIUM',
    LARGE: 'PACKAGE_SIZE.LARGE'
  }
};

